### ISSUE TITLE
怎么控制recyclerview滑动需要的距离

### ISSUE THREAD

**Issue by looooker** [luckyandyzhang/CleverRecyclerView#2]
你好，我现在需要实现一个类似于去哪儿首页的效果，每次横向滑动屏幕宽度，看起来和你的项目差不多，能给点思路吗亲

**Comment by andydevacc** [comment]
@looooker 你是要设置 「触发滚动所需要的距离」吗？ 如果是的话，在CleverRecyclerView里面有个setSlidingThreshold的方法，你可以看看。

**Comment by duanjunxiao** [comment]
您好，我在基于你的CleverRecyclerView做轮播图（类似ViewPager的那种广告）的时候，手动滑动和自动滑动引起冲突了。

**Comment by andydevacc** [comment]
@duanjunxiao 冲突是指？能否具体阐述一下
