### ISSUE TITLE
左右 留出10px 的上一个和下一个 item 的布局

### ISSUE THREAD

**Issue by krmao** [luckyandyzhang/CleverRecyclerView#3]
例如百度地图，高德地图 左右滑动的那种效果

就是可以看到上一个下一个

哥们，一起开发了呗，哈哈

**Comment by andydevacc** [comment]
@mkrcpp 这个功能其实已经实现了，你可以看看 setAdjacentViewDisplayArea 方法。不过可能有点小bug _(:з」∠)_
